### ISSUE TITLE
Installing des

### ISSUE THREAD

**Issue by rimblas** [nicpottier/decent#2]
Nic, what's the correct way to get go and then install/build the project.

Do you like this approach for installing go on the pi?
https://www.e-tinkers.com/2019/06/better-way-to-install-golang-go-on-raspberry-pi/

After that is unclear to me what the correct way to run .goreleaser.yml

go?
go install?
go build?

**Comment by nicpottier** [comment]
I don't generally build on the Pi. If you click on releases there should be
a zip file for the latest which contains an arm binary you should be able
to just copy over and run. Otherwise you would probably cross compile to
arm from your desktop.

**Comment by rimblas** [comment]
Ah gotcha!  I didn't realize it was a compiled file.  Thanks!
got it running now
